<#
deploy.ps1

Usage (from any folder):
  powershell -ExecutionPolicy Bypass -File "C:\path\to\deploy.ps1" -SourceDir "C:\path\to\secure_uploader" -Mode auto

Modes:
  auto  - detect Azure CLI login; deploy to Azure if available, otherwise run locally
  azure - deploy to Azure App Service (requires `az` CLI and login)
  local - create virtualenv, install requirements, and start the dev server

Options:
  -SourceDir <path>   Path to project folder (defaults to script location's parent)
  -AppName <name>     Azure app name (optional; will be autogenerated if not given)
  -ResourceGroup <rg> Azure resource group (defaults to 'secure-uploader-rg')
  -Location <loc>     Azure location (defaults to 'eastus')

This script is intentionally lightweight and safe. It does not modify your repo files.
#>

param(
    [string]$SourceDir = $PSScriptRoot,
    [ValidateSet('auto','azure','local')]
    [string]$Mode = 'auto',
    [string]$AppName = '',
    [string]$ResourceGroup = 'secure-uploader-rg',
    [string]$Location = 'eastus'
)

Set-StrictMode -Version Latest

function Write-Info($m){ Write-Host "[INFO] $m" -ForegroundColor Cyan }
function Write-Err($m){ Write-Host "[ERROR] $m" -ForegroundColor Red }

# Resolve source dir (allow running from anywhere)
$SourceDir = Resolve-Path -Path $SourceDir | Select-Object -ExpandProperty Path
Write-Info "Project source: $SourceDir"

if ($Mode -eq 'auto') {
    if (Get-Command az -ErrorAction SilentlyContinue) {
        try { az account show > $null 2>&1; $azOk = $LASTEXITCODE -eq 0 } catch { $azOk = $false }
        if ($azOk) { $Mode = 'azure'; Write-Info 'Azure CLI detected and logged in — using Azure deployment.' } else { $Mode = 'local'; Write-Info 'Azure CLI not available or not logged in — using local deployment.' }
    } else { $Mode = 'local'; Write-Info 'Azure CLI not installed — using local deployment.' }
}

if ($Mode -eq 'azure') {
    if (-not (Get-Command az -ErrorAction SilentlyContinue)) { Write-Err "Azure CLI not found. Install and login with 'az login'."; exit 2 }

    if (-not $AppName) {
        # create a semi-unique app name
        $rand = -join ((65..90) + (97..122) | Get-Random -Count 6 | ForEach-Object {[char]$_})
        $AppName = "secure-uploader-$rand"
        Write-Info "Generated App name: $AppName"
    }

    # Sanitize app name for Azure (must be alphanumeric or dash, no spaces)
    $AppNameSanitized = ($AppName -replace '[^A-Za-z0-9-]','-').ToLower()
    $AppNameSanitized = $AppNameSanitized.Trim('-')
    if ($AppNameSanitized.Length -lt 3) {
        $AppNameSanitized = "$AppNameSanitized$(Get-Random -Minimum 100 -Maximum 999)"
    }
    if ($AppName -ne $AppNameSanitized) { Write-Info "Using sanitized AppName: $AppNameSanitized (from '$AppName')" }
    $AppName = $AppNameSanitized

    Write-Info "Ensuring resource group '$ResourceGroup' exists in $Location"
    az group create --name $ResourceGroup --location $Location | Out-Null

    Write-Info "Starting Azure App deployment (this will package and deploy the app)."
    # Run `az webapp up` from the project directory (some az versions don't support --src-path)
    Push-Location $SourceDir
    az webapp up --name $AppName --resource-group $ResourceGroup --location $Location --sku F1 --verbose
    $upExit = $LASTEXITCODE
    Pop-Location
    if ($upExit -ne 0) {
        Write-Err 'az webapp up failed; attempting zip deploy fallback.'
        # Fallback: create app service and use zip deploy
        $planName = "$AppName-plan"
        Write-Info "Creating App Service Plan: $planName"
        az appservice plan create --name $planName --resource-group $ResourceGroup --is-linux --sku F1 | Out-Null
        Write-Info "Creating webapp: $AppName"
        # Use single quotes for runtime to avoid PowerShell treating the '|' as a pipeline character
        az webapp create --resource-group $ResourceGroup --plan $planName --name $AppName --runtime 'PYTHON|3.10' | Out-Null
        if ($LASTEXITCODE -ne 0) { Write-Err 'az webapp create failed; check subscription policies and region availability.'; exit 4 }
        # Zip and deploy
        $zipPath = Join-Path $env:TEMP "$AppName-deploy.zip"
        if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
        Write-Info "Creating zip package: $zipPath"
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::CreateFromDirectory($SourceDir, $zipPath)
        Write-Info "Deploying zip to webapp"
        az webapp deployment source config-zip --resource-group $ResourceGroup --name $AppName --src $zipPath | Out-Null
        if ($LASTEXITCODE -ne 0) { Write-Err 'Zip deploy failed.'; exit 3 }
    }

    # Set startup command to use gunicorn to serve Flask app (if gunicorn installed in requirements)
    $startup = 'gunicorn --bind=0.0.0.0:8000 --timeout 120 main:app'
    Write-Info "Configuring startup command: $startup"
    az webapp config set --name $AppName --resource-group $ResourceGroup --startup-file "$startup" | Out-Null

    # Generate simple app settings for encryption key if none provided; keep them private to app
    try { $randkey = [System.Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Maximum 256 } | ForEach-Object {[byte]$_})) } catch { $randkey = [System.Convert]::ToBase64String((New-Object byte[] 32)) }
    Write-Info 'Setting basic app settings (UPLOAD_ENC_KEY and FILESTORE_PASSPHRASE).'
    az webapp config appsettings set --name $AppName --resource-group $ResourceGroup --settings UPLOAD_ENC_KEY=$randkey FILESTORE_PASSPHRASE=$([System.Guid]::NewGuid().ToString()) | Out-Null

    # Create an Azure Storage account to host blobs (uploads). Name must be globally unique and lowercase.
    $storageName = ($AppName -replace '[^a-z0-9]','')
    if ($storageName.Length -gt 20) { $storageName = $storageName.Substring(0,20) }
    $storageName = "$storageName$(Get-Random -Minimum 1000 -Maximum 9999)"
    Write-Info "Creating storage account: $storageName"
    az storage account create --name $storageName --resource-group $ResourceGroup --location $Location --sku Standard_LRS | Out-Null

    Write-Info "Retrieving storage connection string"
    $connStr = az storage account show-connection-string --name $storageName --resource-group $ResourceGroup -o tsv
    if (-not $connStr) { Write-Err "Failed to get storage connection string."; exit 4 }

    $containerName = 'uploads'
    Write-Info "Creating blob container '$containerName' in storage account $storageName"
    az storage container create --name $containerName --account-name $storageName | Out-Null

    Write-Info 'Setting Azure storage app settings for the webapp'
    az webapp config appsettings set --name $AppName --resource-group $ResourceGroup --settings AZURE_STORAGE_CONNECTION_STRING="$connStr" AZURE_BLOB_CONTAINER=$containerName | Out-Null

    Write-Info "Deployment complete. Browse to: https://$AppName.azurewebsites.net (it may take a minute to warm up)."
    exit 0
}

if ($Mode -eq 'local') {
    # Ensure python exists
    $py = Get-Command python -ErrorAction SilentlyContinue
    if (-not $py) { Write-Err "Python not found in PATH. Install Python 3.8+ and try again."; exit 4 }
    $python = $py.Path

    # Create venv inside source (not committed) so the app can be run later from project dir
    $venv = Join-Path $SourceDir '.venv'
    if (-not (Test-Path $venv)) {
        Write-Info "Creating virtualenv at $venv"
        & $python -m venv $venv
    }
    $pip = Join-Path $venv 'Scripts\pip.exe'
    $pyvenv = Join-Path $venv 'Scripts\python.exe'
    if (-not (Test-Path $pip)) { Write-Err "Expected venv pip at $pip not found."; exit 5 }

    Write-Info 'Installing dependencies from requirements.txt'
    & $pip install --upgrade pip setuptools wheel | Out-Null
    $req = Join-Path $SourceDir 'requirements.txt'
    if (Test-Path $req) { & $pip install -r $req } else { Write-Info 'No requirements.txt found; skipping pip install.' }

    # Initialize DB and ensure uploads dir exists by invoking init_db via a small runner
    Write-Info 'Initializing database and ensuring upload folder exists (calls init_db in main.py)'
    Push-Location $SourceDir
    & $pyvenv -c "import main; main.init_db(); print('DB init done')"
    Pop-Location

    Write-Info 'Starting dev server (foreground). Use Ctrl+C to stop.'
    Push-Location $SourceDir
    & $pyvenv main.py
    Pop-Location
    exit 0
}

Write-Err "Unknown mode: $Mode"
exit 1
